[phases.setup]
nixPkgs = ["python3", "nodejs-20", "nodePackages.node-gyp"]
cmds = ["npm ci"]

[phases.install]
cmds = ["npm run prisma:generate"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[plan]
providers = ["nodejs", "npm"]

[nodejs]
version = "20"

[build]
builder = "nixpacks"